spring.application.name=gamestore

    ##Configurar o banco de dados
    spring.datasource.url=jdbc:postgresql://dpg-d6tvgg7gi27c73duuk8g-a.oregon-postgres.render.com/db_deploy_gs_spidemyer
    spring.datasource.username=db_deploy_gs_spidemyer_user
    spring.datasource.password=M2LX28H7wVV3IrrKF2l3XS9iT2CJdDpB
    # obs: nunca colocar senhas em documentos que vão para o github

    ## Configuraçãoes do JPA - hibernate
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=true
    spring.jpa.generate-ddl=true
    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect